import { FaWifi, FaCoffee, FaBath, FaParking, FaSwimmingPool, FaHotdog, FaStopwatch, FaCocktail, FaGlassMartini, FaUmbrellaBeach } from 'react-icons/fa';
import images from '../assets';

export const hotelEntity = 'The GRIPA HOTEL';

export const roomData = [
  {
    id: 1,
    name: 'Superior Room',
    description:
      'Experience ultimate comfort in our Superior Room, featuring elegant decor and modern amenities. Perfect for solo travelers seeking a peaceful retreat with all the essentials for a relaxing stay.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 30,
    maxPerson: 1,
    price: 115,
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: 'Signature Room',
    description:
      'Our Signature Room offers a touch of sophistication with premium furnishings and a cozy layout. Ideal for couples or business travelers who appreciate a blend of style and functionality.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 70,
    maxPerson: 2,
    price: 220,
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: 'Deluxe Room',
    description:
      'The Deluxe Room provides ample space and elevated comfort, designed for those who desire a more luxurious stay. Enjoy beautiful views and refined touches throughout your living space.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 50,
    maxPerson: 3,
    price: 265,
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: 'Luxury Room',
    description:
      'Indulge in pure luxury in this exquisitely designed room. Featuring high-end finishes, a private balcony with stunning views, and a fully stocked mini bar for your enjoyment.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Private Balcony', icon: FaUmbrellaBeach },
      { name: 'Bath', icon: FaBath },
      { name: 'Mini Bar', icon: FaGlassMartini },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 50,
    maxPerson: 4,
    price: 289,
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: 'Luxury Suite Room',
    description:
      'Our most prestigious suite, offering unparalleled space and sophistication. Includes a separate living area, private balcony, and a luxury mini bar, perfect for a truly elite experience.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Private Balcony', icon: FaUmbrellaBeach },
      { name: 'Bath', icon: FaBath },
      { name: 'Mini Bar', icon: FaGlassMartini },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 90,
    maxPerson: 5,
    price: 320,
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: 'Deluxe Room',
    description:
      'Spacious and versatile, this Deluxe Room is perfect for families or groups. Modern amenities and a welcoming atmosphere ensure everyone has a comfortable and memorable stay.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 45,
    maxPerson: 6,
    price: 344,
    image: images.Room6Img,
    imageLg: images.Room6ImgLg,
  },
  {
    id: 7,
    name: 'Luxury Room',
    description:
      'Escape to a world of elegance with our Luxury Room. Whether you are relaxing on the private balcony or enjoying a drink from the mini bar, every moment is crafted for your delight.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Private Balcony', icon: FaUmbrellaBeach },
      { name: 'Bath', icon: FaBath },
      { name: 'Mini Bar', icon: FaGlassMartini },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 84,
    maxPerson: 7,
    price: 389,
    image: images.Room7Img,
    imageLg: images.Room7ImgLg,
  },
  {
    id: 8,
    name: 'Deluxe Room',
    description:
      'A perfect blend of comfort and style, this Deluxe Room offers premium bedding and a spacious layout. Ideal for those who want a quality stay at an exceptional value.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 48,
    maxPerson: 8,
    price: 499,
    image: images.Room8Img,
    imageLg: images.Room8ImgLg,
  },
];
